name: Create PR from Commit SHA

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to create branch and PR from (default: main)'
        required: false
        default: 'main'

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Setup Git and Create Branch
        if: success()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global push.default current
          UUID=$(uuidgen | cut -c-8)  # Generate a short UUID (first 8 characters)
          NEW_BRANCH_NAME=release-$(date +'%m-%d-%Y')-prod-${UUID}
          echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $NEW_BRANCH_NAME ${{ github.event.inputs.commit_sha }}
          git push origin ${{ env.NEW_BRANCH_NAME }}

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          base: release
          branch: ${{ env.NEW_BRANCH_NAME }}
          title: "Merge ${{ env.NEW_BRANCH_NAME }} into Release"
          body: "Release branch generated by GitHub Actions."
